Use robust method of checking provisioning subnet
Use ipcalc for checking that the provisioning interface is a member of
the correct network. This replaces some grep-based shenanigans that made
unjustified assumptions about the format of IPv6 addresses.

It also corrects the behaviour on IPv4 to match IPv6, so that we check
for IPs on the same subnet as the provisioning VIP, not for the exact
provisioning VIP to appear. This should prevent a period of crashlooping
when the metal3 pod moves to a new host.

Also update the error message to reflect the actual semantics, which
are: if the provisioning interface has any IP addresses, one of them
must be for a subnet that also contains the provisioning VIP.

It appears that the purpose of the test is to prevent the provisioning
network being accidentally enabled on a machine network interface, and
reconfiguring that interface. When the provisioning network is managed,
an IP in the provisioning subnet should only appear when this check has
previously succeeded on some other host that was previously running
dnsmasq, so it should be safe to ignore the presence of other IPs. When
the provisioning network is unmanaged it is fine to have other IPs, and
the presence of the provisioning subnet indicates that we have chosen
the correct interface.

diff --git a/set-static-ip b/set-static-ip
--- a/set-static-ip
+++ b/set-static-ip
@@ -21,13 +21,33 @@ if [ -z "${PROVISIONING_INTERFACE}" ]; then
   exit 1
 fi
 
-# Check provisioning interface is already set to ip address
 if [[ -n $(ip -o addr show dev "${PROVISIONING_INTERFACE}" scope global) ]]; then
-  # equality check can be done for IPv4, i.e. 172.22.0.3/24
-  # for IPv6 and dualstack(IPv4v6), fd00:1101::x/64 is used as fd00:1101::xxxx:xxxx:xxxx:xxxx/128
-  # Thus, we need to parse provisioning ip with '::'.
-  if ! ip -o addr show dev "${PROVISIONING_INTERFACE}" scope global | grep -q "${PROVISIONING_IP//::*/}" ; then
-    echo "ERROR: \"$PROVISIONING_INTERFACE\" is already set to ip address belong to different subset than \"$PROVISIONING_IP\""
+
+  function provisioning_net_valid() {
+    local prov_vip_prefixlen
+    prov_vip_prefixlen="$(ipcalc --no-decorate --prefix "${PROVISIONING_IP}")"
+
+    for ip_addr in $(ip -j -o addr show dev "${PROVISIONING_INTERFACE}" | jq -r '.[0].addr_info[] | select(.scope == "global").local'); do
+      # for IPv6 and dualstack(IPv4v6), fd00:1101::x/64 provisioning VIP
+      # has DHCP IP like fd00:1101::xxxx:xxxx:xxxx:xxxx/128
+      # Thus, we need to compare using the VIP's prefix length
+      local host_ip_cidr="${ip_addr}/${prov_vip_prefixlen}"
+      if ! ipcalc --check "${host_ip_cidr}" >/dev/null; then
+          continue
+      fi
+      if [ "$(ipcalc --no-decorate --network "${host_ip_cidr}")" = \
+          "$(ipcalc --no-decorate --network "${PROVISIONING_IP}")" ]; then
+        return 0
+      fi
+    done
+    echo "ERROR: provisioning interface \"${PROVISIONING_INTERFACE}\" IP addresses are all outside the provisioning subnet \"${PROVISIONING_IP}\""
+    return 1
+  }
+
+  # Check that we are not about to reconfigure an interface that is already
+  # configured for a different network, which may indicate that we are dealing
+  # with the machine network.
+  if ! provisioning_net_valid; then
     exit 1
   fi
 fi
